import { expect, test } from '@playwright/test';
import path from 'node:path';

test('wheel zoom and reset keep brushed text aligned for OCR', async ({ page, isMobile }) => {
  test.skip(isMobile, 'Native wheel input is checked in desktop Chromium.');
  test.setTimeout(120_000);
  await page.goto('/');
  await page.getByRole('button', { name: 'Read a photo', exact: true }).click();
  await page.getByLabel('Choose an image', { exact: true }).setInputFiles(path.resolve('tests/fixtures/menu-clean.png'));
  const stage = page.getByRole('group', { name: 'Highlight text in photo' });
  await stage.scrollIntoViewIfNeeded();
  const before = (await stage.boundingBox())!;
  const pageScroll = await page.evaluate(() => scrollY);
  await page.mouse.move(before.x + before.width * .1, before.y + before.height * .45);
  await page.mouse.wheel(0, -450);
  await expect(page.getByLabel('Photo zoom', { exact: true })).not.toHaveText('100%');
  expect(await page.evaluate(() => scrollY)).toBe(pageScroll);
  await page.getByLabel('Brush size', { exact: true }).press('End');
  await stage.scrollIntoViewIfNeeded();
  const image = page.getByRole('img', { name: 'Selected photo prepared for reading' });
  const zoomed = (await image.boundingBox())!;
  expect(zoomed.width).toBeGreaterThan(before.width * 1.5);
  await page.mouse.move(zoomed.x + zoomed.width * .075, zoomed.y + zoomed.height * .45);
  await page.mouse.down();
  await page.mouse.move(zoomed.x + zoomed.width * .20, zoomed.y + zoomed.height * .45, { steps: 8 });
  await page.mouse.up();
  await page.screenshot({ path: test.info().outputPath('zoomed-highlight.png'), fullPage: true });
  await page.getByRole('button', { name: 'Reset zoom', exact: true }).click();
  await expect(page.getByLabel('Photo zoom', { exact: true })).toHaveText('100%');
  await page.getByRole('button', { name: 'Read highlighted text', exact: true }).click();
  const reading = page.getByRole('region', { name: 'Photo reading' });
  await expect(reading.getByText('咖', { exact: true })).toBeVisible({ timeout: 90_000 });
  await expect(reading.getByText('啡', { exact: true })).toBeVisible();
  await expect(reading.getByText('牛', { exact: true })).toHaveCount(0);
  await expect(reading.getByText('旺', { exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Zoom in', exact: true }).click();
  await expect(reading.getByText('咖', { exact: true })).toBeVisible();
});

test('pinch zoom and two-finger pan add no marks before a fresh brush stroke', async ({ page, browserName }) => {
  test.skip(browserName !== 'chromium', 'Native multi-touch injection is available in Chromium.');
  test.setTimeout(120_000);
  await page.goto('/');
  await page.getByRole('button', { name: 'Read a photo', exact: true }).click();
  await page.getByLabel('Choose an image', { exact: true }).setInputFiles(path.resolve('tests/fixtures/menu-clean.png'));
  await page.getByLabel('Brush size', { exact: true }).press('End');
  const stage = page.getByRole('group', { name: 'Highlight text in photo' });
  await stage.scrollIntoViewIfNeeded();
  const bounds = (await stage.boundingBox())!;
  const touch = await page.context().newCDPSession(page);
  const first = { id: 1, x: bounds.x + bounds.width * .15, y: bounds.y + bounds.height * .45 };
  const second = { id: 2, x: bounds.x + bounds.width * .25, y: first.y };
  await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [first] });
  await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [first, second] });
  await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [
    { ...first, x: bounds.x + bounds.width * .10 }, { ...second, x: bounds.x + bounds.width * .30 },
  ] });
  await expect.poll(async () => Number((await page.getByLabel('Photo zoom', { exact: true }).textContent())?.replace('%', ''))).toBeGreaterThan(180);
  const image = page.getByRole('img', { name: 'Selected photo prepared for reading' });
  const beforePan = (await image.boundingBox())!;
  const pannedFirst = { ...first, x: bounds.x + bounds.width * .20 };
  const pannedSecond = { ...second, x: bounds.x + bounds.width * .40 };
  await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [pannedFirst, pannedSecond] });
  await expect.poll(async () => (await image.boundingBox())!.x).toBeGreaterThan(beforePan.x + bounds.width * .05);
  await touch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [pannedSecond] });
  await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ ...pannedFirst, x: pannedFirst.x + 10 }] });
  await touch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  const read = page.getByRole('button', { name: 'Read highlighted text', exact: true });
  await expect(read).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Undo highlight', exact: true })).toBeDisabled();

  const zoomed = (await image.boundingBox())!;
  const brush = { id: 3, x: zoomed.x + zoomed.width * .075, y: zoomed.y + zoomed.height * .45 };
  await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [brush] });
  await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ ...brush, x: zoomed.x + zoomed.width * .20 }] });
  await touch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await read.click();
  const reading = page.getByRole('region', { name: 'Photo reading' });
  await expect(reading.getByText('咖', { exact: true })).toBeVisible({ timeout: 90_000 });
  await expect(reading.getByText('啡', { exact: true })).toBeVisible();
  await expect(reading.getByText('牛', { exact: true })).toHaveCount(0);
  await expect(reading.getByText('旺', { exact: true })).toHaveCount(0);
  await stage.scrollIntoViewIfNeeded();
  const current = (await stage.boundingBox())!;
  const a = { id: 4, x: current.x + current.width * .3, y: current.y + current.height * .5 };
  const b = { id: 5, x: current.x + current.width * .6, y: a.y };
  await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [a] });
  await expect(reading.getByText('咖', { exact: true })).toBeVisible();
  await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [a, b] });
  await touch.send('Input.dispatchTouchEvent', { type: 'touchCancel', touchPoints: [] });
  await expect(reading.getByText('咖', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Undo highlight', exact: true }).click();
  await expect(read).toBeDisabled();

  await touch.detach();
});

test('zoom controls, panning and resizing preserve the selected image pixels', async ({ page }) => {
  test.setTimeout(120_000);
  await page.goto('/');
  await page.getByRole('button', { name: 'Read a photo', exact: true }).click();
  const picker = page.getByLabel('Choose an image', { exact: true });
  await picker.setInputFiles(path.resolve('tests/fixtures/menu-clean.png'));
  await page.getByLabel('Brush size', { exact: true }).press('End');
  const zoomIn = page.getByRole('button', { name: 'Zoom in', exact: true });
  await zoomIn.click();
  await zoomIn.click();
  const stage = page.getByRole('group', { name: 'Highlight text in photo' });
  await page.getByRole('button', { name: 'Move photo', exact: true }).click();
  await stage.scrollIntoViewIfNeeded();
  const bounds = (await stage.boundingBox())!;
  await page.mouse.move(bounds.x + bounds.width * .2, bounds.y + bounds.height * .5);
  await page.mouse.down();
  await page.mouse.move(bounds.x + bounds.width * .75, bounds.y + bounds.height * .5, { steps: 8 });
  await page.mouse.up();
  const read = page.getByRole('button', { name: 'Read highlighted text', exact: true });
  await expect(read).toBeDisabled();
  await page.getByRole('button', { name: 'Brush', exact: true }).click();
  await stage.scrollIntoViewIfNeeded();
  const image = page.getByRole('img', { name: 'Selected photo prepared for reading' });
  const zoomed = (await image.boundingBox())!;
  await page.mouse.move(zoomed.x + zoomed.width * .075, zoomed.y + zoomed.height * .45);
  await page.mouse.down();
  await page.mouse.move(zoomed.x + zoomed.width * .20, zoomed.y + zoomed.height * .45, { steps: 8 });
  await page.mouse.up();
  const viewport = page.viewportSize()!;
  await page.setViewportSize({ ...viewport, width: Math.max(320, viewport.width - 80) });
  await page.getByRole('button', { name: 'Reset zoom', exact: true }).click();
  await read.click();
  const reading = page.getByRole('region', { name: 'Photo reading' });
  await expect(reading.getByText('咖', { exact: true })).toBeVisible({ timeout: 90_000 });
  await expect(reading.getByText('啡', { exact: true })).toBeVisible();
  await expect(reading.getByText('牛', { exact: true })).toHaveCount(0);
  await expect(reading.getByText('旺', { exact: true })).toHaveCount(0);
  for (let i = 0; i < 5; i++) await zoomIn.click();
  await expect(page.getByLabel('Photo zoom', { exact: true })).toHaveText('600%');
  await expect(zoomIn).toBeDisabled();
  await expect(reading.getByText('咖', { exact: true })).toBeVisible();
  await picker.setInputFiles(path.resolve('tests/fixtures/orientation-6.jpg'));
  await expect(page.getByLabel('Photo zoom', { exact: true })).toHaveText('100%');
  await expect(page.getByRole('button', { name: 'Zoom out', exact: true })).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Undo highlight', exact: true })).toBeDisabled();
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
});

test('switching from keyboard to pointer preserves both highlight strokes', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Read a photo', exact: true }).click();
  await page.getByLabel('Choose an image', { exact: true }).setInputFiles(path.resolve('tests/fixtures/menu-clean.png'));
  const stage = page.getByRole('group', { name: 'Highlight text in photo' });
  await stage.scrollIntoViewIfNeeded();
  await stage.focus();
  await stage.press('Space');
  await stage.press('ArrowLeft');
  const bounds = (await stage.boundingBox())!;
  await page.mouse.move(bounds.x + bounds.width * .08, bounds.y + bounds.height * .2);
  await page.mouse.down();
  await page.mouse.move(bounds.x + bounds.width * .28, bounds.y + bounds.height * .2, { steps: 6 });
  await page.mouse.up();
  const read = page.getByRole('button', { name: 'Read highlighted text', exact: true });
  await page.getByRole('button', { name: 'Undo highlight', exact: true }).click();
  await expect(read).toBeEnabled();
  await page.getByRole('button', { name: 'Undo highlight', exact: true }).click();
  await expect(read).toBeDisabled();
});

test('keyboard brushing returns to the visible photo after zooming and panning', async ({ page }) => {
  test.setTimeout(120_000);
  await page.goto('/');
  await page.getByRole('button', { name: 'Read a photo', exact: true }).click();
  await page.getByLabel('Choose an image', { exact: true }).setInputFiles(path.resolve('tests/fixtures/menu-clean.png'));
  await page.getByLabel('Brush size', { exact: true }).press('End');
  const stage = page.getByRole('group', { name: 'Highlight text in photo' });
  await stage.focus();
  for (let i = 0; i < 20; i++) { await stage.press('ArrowRight'); await stage.press('ArrowDown'); }
  const zoomIn = page.getByRole('button', { name: 'Zoom in', exact: true });
  for (let i = 0; i < 3; i++) await zoomIn.click();
  await page.getByRole('button', { name: 'Move photo', exact: true }).click();
  await stage.scrollIntoViewIfNeeded();
  const bounds = (await stage.boundingBox())!;
  await page.mouse.move(bounds.x + bounds.width * .05, bounds.y + bounds.height * .5);
  await page.mouse.down();
  await page.mouse.move(bounds.x + bounds.width * .95, bounds.y + bounds.height * .5, { steps: 8 });
  await page.mouse.up();
  // Finish moving to the left edge while keeping the old keyboard cursor out of view.
  await page.mouse.move(bounds.x + bounds.width * .2, bounds.y + bounds.height * .5);
  await page.mouse.down();
  await page.mouse.move(bounds.x + bounds.width * .7, bounds.y + bounds.height * .5, { steps: 8 });
  await page.mouse.up();
  await page.getByRole('button', { name: 'Brush', exact: true }).click();
  await stage.focus();
  for (let i = 0; i < 8; i++) await stage.press('ArrowUp');
  for (let i = 0; i < 5; i++) await stage.press('ArrowLeft');
  await stage.press('Space');
  for (let i = 0; i < 10; i++) await stage.press('ArrowRight');
  await stage.press('Space');
  await page.getByRole('button', { name: 'Read highlighted text', exact: true }).click();
  const reading = page.getByRole('region', { name: 'Photo reading' });
  await expect(reading.getByText('咖', { exact: true })).toBeVisible({ timeout: 15_000 });
  await expect(reading.getByText('啡', { exact: true })).toBeVisible();
  await expect(reading.getByText('牛', { exact: true })).toHaveCount(0);
  await expect(reading.getByText('旺', { exact: true })).toHaveCount(0);
});
